### ISSUE TITLE
W25Q_EraseBlock return W25Q_PARAM_ERR

### ISSUE THREAD

**Issue by fresird** [Crazy-Geeks/STM32-W25Q-QSPI#1]
size == 32 || size == 64 will return W25Q_PARAM_ERR.
I think Line 859 should be changed to 
	if (size != 32 && size != 64)
/**
 * @brief W25Q Block erase (32/64 KB)
 * Func to erase big block
 *
 * @note Should be executed before writing
 * @param[in] BlockAddr Block start address
 * @param[in] size Size of block: 32KB or 64KB
 * @return W25Q_STATE enum
 */
W25Q_STATE W25Q_EraseBlock(u32_t BlockAddr, u8_t size) {
	if (size != 32 || size != 64)          <------------------------------------
		return W25Q_PARAM_ERR;
	if ((size == 64 && BlockAddr >= BLOCK_COUNT)
			|| (size == 32 && BlockAddr >= BLOCK_COUNT * 2))
		return W25Q_PARAM_ERR;

**Comment by Crazy-Geeks** [comment]
@fresird, Thanks for notice

**Comment by fresird** [comment]
Hi @Crazy-Geeks , Thanks you for your great W25Q library.
I find if I write 256 bytes with pageShift == 0, W25Q_ProgramData return W25Q_PARAM_ERR.
I changed 255 to 256, and It works very well.
W25Q_STATE W25Q_ProgramData(uint8_t* buf, uint16_t len, uint8_t pageShift, uint32_t pageNum)
{
	/*
    if (pageNum >= PAGE_COUNT || len == 0 || len > 256 || pageShift > 255 - len
        || (pageShift > 0 && pageNum >= PAGE_COUNT - 1))
        return W25Q_PARAM_ERR;
    */
    if (pageNum >= PAGE_COUNT || len == 0 || len > 256 || pageShift > 256 - len
        || (pageShift > 0 && pageNum >= PAGE_COUNT - 1))
        return W25Q_PARAM_ERR;    
    uint32_t rawAddr = page_to_addr(pageNum, pageShift);
    return W25Q_ProgramRaw(buf, len, rawAddr);
}

**Comment by Crazy-Geeks** [comment]
@fresird  I haven't tested it well, so I've missed this error, I'll fix this. 
If you find bugs later - create pull request, please
